version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BillingNotifer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nd4fj3ryky5d"
s3_prefix = "BillingNotifer"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
